app:
  build: .
web:
  extends:
    service: app
  command: gunicorn -b 0.0.0.0:8000 --reload measurements.wsgi --workers 4 --timeout 120
  ports:
    - "8000"
  links:
    - redis
    - rabbitmq
https-portal:
  image: steveltn/https-portal:1.0.0
  ports:
    - "80:80"
    - "443:443"
  links:
    - web

redis:
  image: redis:latest

rabbitmq:
  image: rabbitmq:latest

worker:
  extends:
    service: app
  command: celery -A measurements.runcelery.celery worker -l info
  links:
    - redis
    - rabbitmq

beat:
  extends:
    service: app
  command: celery -A measurements.runcelery.celery beat -l info
  links:
    - redis
    - rabbitmq
