version: '3.9'

services:
  db:
    image: postgres:11.12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ooni
      POSTGRES_USER: metadb

  api:
    restart: always
    build:
      context: .
    command: gunicorn3 --reuse-port ooniapi.wsgi --statsd-host 127.0.0.1:8125
    volumes:
      - ./newapi/:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
