db:
  image: postgres:9.5
  ports:
    # I have another postgres running on this port.
    - "5433:5432"

app:
  build: .
  environment:
    APP_ENV: development
    DATABASE_URL: postgresql://postgres@db/measurements

web:
  extends:
    service: app
  command: gunicorn -b 0.0.0.0:8000 --reload measurements.wsgi --workers 4
  environment:
    WEBSERVER_PORT: 8000
  ports:
    - "80:8000"
  links:
    - db
