app:
  build: .
web:
  extends:
    service: app
  command: gunicorn -b 0.0.0.0:8000 --reload measurements.wsgi --workers 4 --timeout 120

redis:
  image: redis:latest

rabbitmq:
  image: rabbitmq:latest

worker:
  extends:
    service: app
  command: celery -A measurements.runcelery.celery worker -l info

beat:
  extends:
    service: app
  command: celery -A measurements.runcelery.celery beat -l info
