version: 0.2
env:
  variables:
    OONI_CODE_PATH: ooniapi/services/oonirun
    DOCKERHUB_SECRET_ID: oonidevops/dockerhub/access_token
    LANG: en_US.UTF-8
    LANGUAGE: en_US.UTF-8
    LC_CTYPE: en_US.UTF-8
    LC_ALL: en_US.UTF-8

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - mkdir -p /home/codebuild-user
      - cp -R ${CODEBUILD_SRC_DIR}/ooniapi /home/codebuild-user/ooniapi/
      - locale-gen --purge "en_US.UTF-8"
      - dpkg-reconfigure --frontend noninteractive locales
      - echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
      - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
      - apt-get update
      - apt install -y postgresql-16
      # run-as: codebuild-user is a mess: https://stackoverflow.com/questions/51365622/aws-codebuild-as-non-root-user
      - chmod 666 /var/run/docker.sock
      - chmod +x /home/codebuild-user
      - chmod +x /root/
      - chown -R codebuild-user:codebuild-user /root/.pyenv
      - chown -R codebuild-user:codebuild-user /home/codebuild-user
      - ls -ld /home/codebuild-user

  pre_build:
    commands:
      - echo "Logging in to dockerhub"
      - >
        aws secretsmanager get-secret-value --secret-id $DOCKERHUB_SECRET_ID --query SecretString --output text
          | docker login --username ooni --password-stdin

  build:
    run-as: codebuild-user
    commands:
      - pip install hatch
      - export HOME=/home/codebuild-user
      - cd /home/codebuild-user/$OONI_CODE_PATH
      - export GIT_FULL_SHA=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - make test
      - make clean
      - make imagedefinitions.json

artifacts:
  files: imagedefinitions.json
