web:
  env_file:
  - ./base.env
  - ./development.env
  - ./secrets.env
  command: python -m measurements run -p 3000 -h 0.0.0.0 --reload
  ports:
    - "3000:3000"
  volumes:
    - ./measurements:/app/measurements:z
    - ./dev:/app/dev:z
static:
  extends:
    service: app
  command: gulp watch
  volumes:
    - ./measurements:/app/measurements:z
