web:
  env_file:
  - ./config/base.env
  - ./config/production.env
  - /opt/secrets.env
worker:
  env_file:
  - ./config/base.env
  - ./config/production.env
  - /opt/secrets.env
beat:
  env_file:
  - ./config/base.env
  - ./config/production.env
  - /opt/secrets.env
https-portal:
  env_file:
  - ./config/production.env
