web:
  env_file:
  - ./config/base.env
  - ./config/production.env
  - /opt/secrets.env
  ports:
  - "8000"
  links:
  - redis
  - rabbitmq

worker:
  env_file:
  - ./config/base.env
  - ./config/production.env
  - /opt/secrets.env
  links:
    - redis
    - rabbitmq

beat:
  env_file:
  - ./config/base.env
  - ./config/production.env
  - /opt/secrets.env
  links:
    - redis
    - rabbitmq

https-portal:
  image: steveltn/https-portal:1.0.0
  env_file:
  - ./config/production.env
  ports:
    - "80:80"
    - "443:443"
  links:
    - web
