web:
  env_file:
  - ./config/base.env
  - ./config/production.env
  - /opt/secrets.env
  ports:
  - "8000"

worker:
  env_file:
  - ./config/base.env
  - ./config/production.env
  - /opt/secrets.env

beat:
  env_file:
  - ./config/base.env
  - ./config/production.env
  - /opt/secrets.env

https-portal:
  image: steveltn/https-portal:1.0.0
  restart: always
  env_file:
  - ./config/production.env
  ports:
    - "80:80"
    - "443:443"
  links:
    - web
