db:
  image: postgres:9.5
  ports:
    - "5433:5432"

web:
  env_file:
  - ./config/base.env
  - ./config/testing.env
  - /opt/secrets.env
  volumes:
    - ./measurements:/app/measurements:z
    - ./dev:/app/dev
  ports:
    - "80:8000"
  links:
    - db
    - redis
    - rabbitmq

worker:
  env_file:
  - ./config/base.env
  - ./config/testing.env
  - /opt/secrets.env
  volumes:
    - ./measurements:/app/measurements:z
    - ./dev:/app/dev
  links:
    - db
    - redis
    - rabbitmq

beat:
  env_file:
  - ./config/base.env
  - ./config/testing.env
  - /opt/secrets.env
  volumes:
    - ./measurements:/app/measurements:z
    - ./dev:/app/dev
  links:
    - db
    - redis
    - rabbitmq
