name: OONI API tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    # Implemented based on:
    # https://help.github.com/en/actions/configuring-and-managing-workflows/creating-postgresql-service-containers
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      # Cache the pip dependencies
      # https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#caching-dependencies
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install -U pip setuptools wheel codecov
          pip install -r requirements/main.txt
          pip install -r requirements/tests.txt
          sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Init the databse
        run: bash scripts/init_db.sh
        env:
          POSTGRES_HOST: 127.0.0.1
          PGPASSWORD: postgres
          PGPORT: 5432
      - name: Run tests
        run: make APP_ENV=production test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ooni_measurements
