name: OONI API local tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run tests
        run: docker-compose run api pytest-3 -s --show-capture=no -s -vv -k test_list_me
